### PR TITLE
ask devs to review

### PR DESCRIPTION
**Pull request by nsb**
I think it's better to let people themselves take on review tasks than assigning other people directly. That way everyone can participate in reviewing and you don't have to wait for that specific person to have time.

### CODE REVIEW

**Comment by JanNash** [comment]
But in that case, you could also assign multiple people to a PR?

**Comment by JanNash** [comment]
Also, we might need a consensus on how many people have to approve a PR then. Is one sufficient? Should we require more approvals for very critical parts of the app (i.e. availabilities, create_booking, etc.)?

**Comment by JanNash** [comment]
The problem we want to solve with assigning people to PRs is that a PR tends to lie around for a while when noone feels really responsible for it. When someone is assigned a PR, they feel more responsible for it and if they unassign themselves, they should maybe even give a reason in a comment and assign someone else (which we might want to add to the guidelines?).
@menor whaddoyouthink?

**Comment by menor** [comment]
I prefer the assigning causes it forces me to look at the pull requests I'm assigned to, if not I don't feel responsible for them and I move to tasks more fun to me than code reviewing, but that's just me. I'll go with consensus.

**Comment by nsb** [comment]
I will close this one.

**Pull request closed without merging**
