### PR TITLE
Add priority and size labels

### LINKED ISSUE #12: Define labels for size and priority categories
Size labels specify the estimated amount of time an issue is going to take to complete. Proposed color is #FF7F50 (Coral)

Labels:
- `x-small`:  You only need one cup of coffee to finish it
- `small`:  < ☕️☕️☕️  (3)
- `medium`: < ☕️☕️☕️☕️☕️  (5)
- `large`: < ☕️☕️☕️☕️☕️☕️☕️☕️☕️☕️  (10)
- `x-large`: Split it into a project with more manageable chunks

Priority labels can be assigned by product managers as long as they don't abuse them ;) Proposed color is #FF1493 (Deep Pink)

Labels: 
- `P1`: Critical, drop whatever you are working on and work on this.
- `P2`: Must. Must be finished this milestone.
- `P3`: Should. Should be finished this milestone.

### PR DESCRIPTION
**Pull request by menor**
closes #12

### CODE REVIEW

**Comment by JannKleen** [comment]
@menor we talked about a different distribution of points and re-introducing x-large in #12 , any reason we're using your initial suggestion now?

**Comment by menor** [comment]
Ok sorry I didn't understand the point distribution thing, so you mean:
```
x-small: 1 coffee
small: 3
medium: 5
large: 8
x-large: 13
```
Right?

About bringing the x-large back, I [commented about it](https://github.com/resmio/git-along/issues/12#issuecomment-247922194) and assumed silence implies consent. But we can keep debating in #12.

**Comment by menor** [comment]
this is an useless comment just to tests a notification

**Comment by JanNash** [comment]
I think it's 1, 2, 5, 8, 13, (non-zero) numbers 2-6 of the Fibonacci-sequence.

**Pull request merged**
